apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api                            # Routes traffic to pods with label "app: api"
  ports:
    - protocol: TCP
      port: 5000                        # Expose port 5000 for external access
      targetPort: 5000                  # Maps to container port 5000
  type: ClusterIP                        # Internal cluster service
