name: Build and Push API Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: shared-actions-repo/.github/workflows/build-and-push.yml@main
    with:
      ecr-repo-uri: ${{ secrets.ECR_API_REPO_URI }}
      dockerfile-path: ./Dockerfile
      context-path: .
